### ISSUE TITLE
Wrong path returned

### ISSUE THREAD

**Issue by orefalo** [VeliovGroup/Meteor-root#2]
In order to get the project path, the following should be added

.split('.meteor')[0];

actually, the proper way to get this info with M1.2.1 is 

```
__meteor_bootstrap__.serverDir.split('.meteor')[0]
```

**Comment by dr-dimitru** [comment]
Thank you, I gree to change to `__meteor_bootstrap__.serverDir`. 
But not to your suggestion with split, cause it will break currently existent apps. This package have to return directory where server is running and it includes `/.meteor/local/build/programs/server` or similar for production.

**Comment by orefalo** [comment]
ok - then you need a few adjustments in your pkg description.

starting with the usage...
var pathToFile = Meteor.rootPath + '/folder/where/is/your/file.json';

why would I deploy a file.json under the server path?

wasn't the projectRoot the original intent?

regard less.. .maybe a Meteor.projectRootPath and Meteor.rootPath ?

Cheers

**Comment by dr-dimitru** [comment]
> `var pathToFile = Meteor.rootPath + '/folder/where/is/your/file.json';`

Right after it:

> Returns absolute path to `programs/server` folder of your compiled application

**Comment by dr-dimitru** [comment]
@orefalo usually you want to get files relative to project's directory, otherwise you will exactly know where file is

**Comment by dr-dimitru** [comment]
done in c2978b2dd76248156aef97541905e11fa1ed1fcf
Thank you

**Comment by orefalo** [comment]
tks
