### ISSUE TITLE
Meteor 1.3 support

### ISSUE THREAD

**Issue by konard** [VeliovGroup/Meteor-root#5]
Looks like Meteor 1.3 introduces new way to get the same results, looks like we should use build in version if it is available otherwise use current logic (http://stackoverflow.com/a/37590376/710069)

`Assets.absoluteFilePath(assetPath)`

**Comment by dr-dimitru** [comment]
Not sure...
Could you send example PR?

**Comment by dr-dimitru** [comment]
@Konard any update on this one?

**Comment by konard** [comment]
No, I didn`t started it yet. If I have free time, I'll tell about it here.

**Comment by dr-dimitru** [comment]
Hi @Konard ,

Will we change current code? Seems like everyone else is satisfied with current solution...

**Comment by konard** [comment]
Yes, sure. If it works, let it be. If it brakes, we can fix it. I think this issue can be closed for now.
