### ISSUE TITLE
Path vars switched

### ISSUE THREAD

**Issue by mgscreativa** [VeliovGroup/Meteor-root#7]
Hi! I think the documentation is missing the value of the correct vars. Here is what I get from root and absolute paths:

> Absolute Path: /home/user/Meteor/app
> Root Path: /home/user/Meteor/app/.meteor/local/build/programs/server

**Comment by dr-dimitru** [comment]
Hi @mgscreativa ,

Didn't get what looks misleading to you?

**Comment by dr-dimitru** [comment]
Just published [tests](https://github.com/VeliovGroup/Meteor-root/blob/master/meteor-root-test.js) against this ticket. Everything is fine.

Try it yourself by cloning this project and running `meteor test-packages ./`

**Comment by mgscreativa** [comment]
The readme states:

> Meteor.rootPath: Returns absolute path to programs/server folder of your compiled application, without trailing slash
> 
> Meteor.absolutePath: Returns absolute path to .meteor folder of your compiled application, without trailing slash

But I got 

> Root Path: /home/user/Meteor/app/.meteor/local/build/programs/server
> Absolute Path: /home/user/Meteor/app

It seems that rootPath is returning absolute path to .meteor folder and absolutePath is returning absolute path to programs/server folder.
