### ISSUE TITLE
Wrong path in test-mode

### ISSUE THREAD

**Issue by SimonSimCity** [VeliovGroup/Meteor-root#8]
Doesn't work in test-mode ... It always returns a path like `/private/var/folders/qb/j_vlz31s2wn7v0vn7jhz5bvc0000gn/T/meteor-test-runowob50.z6tz` - at least on my Mac OS X using Meteor v1.6.0.1

**Comment by dr-dimitru** [comment]
@SimonSimCity Looks fine to me, what is the question?

**Comment by SimonSimCity** [comment]
@dr-dimitru If I run this in development mode I get the correct value, which is `/User/simon/test-project`.

In test-mode I'd get the correct value by using `process.env.PWD` - but this environment variable is not available on windows. I wasn't yet able to start my project on Windows in test-mode. Do you have a chance to check what value you get there?

**Comment by dr-dimitru** [comment]
`PWD` is the place (*directory, folder*) where command was executed. Our lib gives you path where running script is located. Tests are build and executed from temporary locations

**Comment by SimonSimCity** [comment]
@dr-dimitru Ok, please state this in your readme as well, because I e.g. need to find a library that can give me the path of my meteor project that is currently running in order to access files relative to this path. I want to save the code-coverage, registered during tests, to be saved in the folder `.coverage` of my project :wink:

**Comment by dr-dimitru** [comment]
@SimonSimCity title and main description:

> Get current path on server, where is __Meteor application is running__


> Returns absolute path to `programs/server` folder of your __compiled application__, without trailing slash

And in case of running tests it's compiled at temporary directories

**Comment by SimonSimCity** [comment]
I rather thought of a note to clarify that this doesn't necessarily is the root of your project folder - just to avoid confusion for people who are not that deep into Meteor.

**Comment by dr-dimitru** [comment]
@SimonSimCity there is various ways to make our docs better:
 1. Send a PR if you wish, PRs are always welcome;
 2. If you can not send a PR, provide a suggestion to our Readme.md right at this thread;

**Comment by SimonSimCity** [comment]
I'd add something like this to the `Readme.md` below the example of `Meteor.absolutePath`:

> **Note:** Be aware of that the path, returned by `Meteor.absolutePath` returns the location from where your Meteor application is running from. This is not guaranteed to be the same as the the path of your project. Running Meteor in test-mode for example will return a path of in a temporary location.

I'm not a native english speaker so it might not exactly hit the point, but at least should clarify it a bit :wink:

**Comment by dr-dimitru** [comment]
@SimonSimCity thank you for this suggestion. Docs are updated in [`v1.0.7`](https://github.com/VeliovGroup/Meteor-root/releases/tag/1.0.7). 🎉🎉🎉
